# Generated by Django 4.2.7 on 2024-06-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_options_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-id']},
        ),
    ]
